# ============================================================
# SURAKSHA AI — Indian Insurance Policy Catalog
# Maps ML predictions to real Indian insurance products
# ============================================================

POLICY_CATALOG = [
    # ── HEALTH POLICIES ────────────────────────────────────────
    {
        "id": "H001",
        "name": "Star Health Comprehensive",
        "insurer": "Star Health Insurance",
        "type": "health",
        "min_age": 18, "max_age": 65,
        "min_income": 200000,
        "ideal_bmi_range": (18.5, 30),
        "smoker_ok": True,
        "min_sum_insured": 500000,
        "max_sum_insured": 10000000,
        "premium_base": 8000,
        "premium_per_lakh": 1200,
        "features": [
            "Cashless at 10,000+ hospitals",
            "No room rent capping",
            "Mental health cover included",
            "Alternative treatment (AYUSH) covered",
            "Annual health checkup free",
        ],
        "best_for": "young_families",
        "charge_range": (0, 15000),   # dataset charges range
        "family_size_weight": 1.2,
    },
    {
        "id": "H002",
        "name": "HDFC Ergo Optima Restore",
        "insurer": "HDFC Ergo",
        "type": "health",
        "min_age": 18, "max_age": 65,
        "min_income": 300000,
        "ideal_bmi_range": (18.5, 35),
        "smoker_ok": True,
        "min_sum_insured": 300000,
        "max_sum_insured": 5000000,
        "premium_base": 7000,
        "premium_per_lakh": 1100,
        "features": [
            "Restore benefit — sum insured restored after claim",
            "No co-payment",
            "Day care procedures covered",
            "Organ donor expenses covered",
            "Multiplier benefit for claim-free years",
        ],
        "best_for": "middle_income",
        "charge_range": (5000, 25000),
        "family_size_weight": 1.1,
    },
    {
        "id": "H003",
        "name": "Niva Bupa ReAssure 2.0",
        "insurer": "Niva Bupa",
        "type": "health",
        "min_age": 18, "max_age": 60,
        "min_income": 500000,
        "ideal_bmi_range": (18.5, 28),
        "smoker_ok": False,
        "min_sum_insured": 1000000,
        "max_sum_insured": 30000000,
        "premium_base": 12000,
        "premium_per_lakh": 900,
        "features": [
            "Booster benefit — up to 100% bonus annually",
            "Lock the clock — age locked at entry",
            "Direct claim settlement",
            "No pre-policy medical test up to 45 years",
            "International emergency cover",
        ],
        "best_for": "high_income_non_smokers",
        "charge_range": (10000, 50000),
        "family_size_weight": 1.0,
    },
    # ── TERM LIFE POLICIES ─────────────────────────────────────
    {
        "id": "T001",
        "name": "LIC Tech Term Plan",
        "insurer": "Life Insurance Corporation of India",
        "type": "term",
        "min_age": 18, "max_age": 65,
        "min_income": 150000,
        "ideal_bmi_range": (0, 40),
        "smoker_ok": True,
        "min_sum_insured": 5000000,
        "max_sum_insured": 200000000,
        "premium_base": 6000,
        "premium_per_lakh": 80,
        "features": [
            "Govt-backed trust and security",
            "₹1 Crore cover at ~₹700/month",
            "Online purchase — no agent required",
            "Return of premium option available",
            "Accidental death benefit rider",
        ],
        "best_for": "government_employees_risk_averse",
        "charge_range": (0, 20000),
        "family_size_weight": 1.3,
    },
    {
        "id": "T002",
        "name": "HDFC Click 2 Protect Super",
        "insurer": "HDFC Life",
        "type": "term",
        "min_age": 18, "max_age": 65,
        "min_income": 300000,
        "ideal_bmi_range": (0, 35),
        "smoker_ok": True,
        "min_sum_insured": 10000000,
        "max_sum_insured": 500000000,
        "premium_base": 8000,
        "premium_per_lakh": 70,
        "features": [
            "Income replacement option",
            "Cover continuance on critical illness",
            "Decreasing cover for loan protection",
            "Waiver of premium on disability",
            "99.5% claim settlement ratio",
        ],
        "best_for": "salaried_with_loans",
        "charge_range": (5000, 40000),
        "family_size_weight": 1.2,
    },
    # ── CRITICAL ILLNESS ───────────────────────────────────────
    {
        "id": "C001",
        "name": "ICICI Pru Heart & Cancer Protect",
        "insurer": "ICICI Prudential",
        "type": "critical_illness",
        "min_age": 20, "max_age": 65,
        "min_income": 400000,
        "ideal_bmi_range": (18.5, 32),
        "smoker_ok": False,
        "min_sum_insured": 1000000,
        "max_sum_insured": 30000000,
        "premium_base": 10000,
        "premium_per_lakh": 500,
        "features": [
            "Covers 64 critical illnesses",
            "Lump sum payout on diagnosis",
            "No hospitalization required to claim",
            "Cancer + Heart disease dual cover",
            "Income benefit option",
        ],
        "best_for": "high_risk_smokers_family_history",
        "charge_range": (15000, 65000),
        "family_size_weight": 0.9,
    },
    # ── SENIOR CITIZEN ─────────────────────────────────────────
    {
        "id": "S001",
        "name": "Star Senior Citizen Red Carpet",
        "insurer": "Star Health Insurance",
        "type": "senior_health",
        "min_age": 60, "max_age": 75,
        "min_income": 100000,
        "ideal_bmi_range": (18.5, 35),
        "smoker_ok": True,
        "min_sum_insured": 100000,
        "max_sum_insured": 2500000,
        "premium_base": 15000,
        "premium_per_lakh": 2500,
        "features": [
            "No pre-acceptance medical test",
            "Pre-existing diseases covered from day 1",
            "Domiciliary treatment covered",
            "Teleconsultation included",
            "Emergency ambulance covered",
        ],
        "best_for": "senior_citizens",
        "charge_range": (20000, 65000),
        "family_size_weight": 1.0,
    },
    # ── FAMILY FLOATER ─────────────────────────────────────────
    {
        "id": "F001",
        "name": "Bajaj Allianz Health Guard Family Floater",
        "insurer": "Bajaj Allianz",
        "type": "family_floater",
        "min_age": 18, "max_age": 65,
        "min_income": 250000,
        "ideal_bmi_range": (0, 40),
        "smoker_ok": True,
        "min_sum_insured": 300000,
        "max_sum_insured": 5000000,
        "premium_base": 9000,
        "premium_per_lakh": 950,
        "features": [
            "Entire family under one sum insured",
            "Maternity benefit included",
            "Newborn baby cover from day 1",
            "Vaccination expenses covered",
            "E-opinion from international doctors",
        ],
        "best_for": "young_families_with_children",
        "charge_range": (5000, 30000),
        "family_size_weight": 1.5,
    },
    # ── INVESTMENT + INSURANCE ─────────────────────────────────
    {
        "id": "U001",
        "name": "SBI Life eWealth Insurance (ULIP)",
        "insurer": "SBI Life",
        "type": "ulip",
        "min_age": 18, "max_age": 55,
        "min_income": 500000,
        "ideal_bmi_range": (0, 40),
        "smoker_ok": True,
        "min_sum_insured": 500000,
        "max_sum_insured": 50000000,
        "premium_base": 12000,
        "premium_per_lakh": 600,
        "features": [
            "Market-linked returns + life cover",
            "Tax benefits under 80C and 10(10D)",
            "Flexible fund switching",
            "Partial withdrawal after 5 years",
            "Top-up premium facility",
        ],
        "best_for": "high_income_investors",
        "charge_range": (20000, 65000),
        "family_size_weight": 0.8,
    },
    # ── ACCIDENT ───────────────────────────────────────────────
    {
        "id": "A001",
        "name": "Tata AIG Accident Guard",
        "insurer": "Tata AIG",
        "type": "accident",
        "min_age": 18, "max_age": 70,
        "min_income": 100000,
        "ideal_bmi_range": (0, 50),
        "smoker_ok": True,
        "min_sum_insured": 500000,
        "max_sum_insured": 15000000,
        "premium_base": 2000,
        "premium_per_lakh": 150,
        "features": [
            "24/7 worldwide accident cover",
            "Permanent disability payout",
            "Daily hospital cash allowance",
            "Education benefit for children",
            "Loan EMI protection",
        ],
        "best_for": "manual_workers_field_jobs",
        "charge_range": (0, 15000),
        "family_size_weight": 1.1,
    },
]

def get_policy_by_id(policy_id: str) -> dict:
    for p in POLICY_CATALOG:
        if p["id"] == policy_id:
            return p
    return {}

def get_policies_by_type(policy_type: str) -> list:
    return [p for p in POLICY_CATALOG if p["type"] == policy_type]